### ISSUE TITLE
Feature Request: Find and Replace function

### ISSUE THREAD

**Issue by p2635** [jamiemcg/Remarkable#21]
Might be useful :)

**Comment by johann-petrak** [comment]
This is hands down the most important missing feature (and apparently the most requested as well): any editor without find/replace is seriously limited. 

Is it very difficult to add this? Given that the label "priority" has been added in 2016 one starts to think it might be ... 

Maybe it would make sense to pin the issue so that others who are looking for this can spot it more easily and maybe get motivated to contribute a pull request?
