### ISSUE TITLE
Gitlab Flavored Markdown and Katex 

### ISSUE THREAD

**Issue by jfellus** [jamiemcg/Remarkable#272]
I use Gitlab Flavored Markdown which the following markup 
````
$``$
````
and 
````
```math
```
````
to insert math equations (https://docs.gitlab.com/ee/user/markdown.html#math)

Is there any easy customization to the code I can make to obtain the right behavior with this flavor ?
For now, in Github Flavored Markdown, this displays $` `` `$

**Comment by ckingdev** [comment]
This is pretty old now, but if I remember the problem correctly Remarkable has support for MathJax- so `$\alpha$` should get you an inline alpha, `$$\alpha$$` would get a display equation- however,  Remarkable doesn't include MathJax directly, it's included in a `<script>` in the rendered html from a CDN. The problem is that the CDN used is no longer providing MathJax, and so including the js fails silently and the math is formatted as raw text.

The solution is to replace the url in the script include to a different CDN. That's it! But it's buried in a string literal in a pretty large Python file, not as any user-facing configuration option, so you'll need to edit that Python file. If you search the issues for "mathjax"' there are some about this that have solutions in the comments, otherwise, when I can get back to my computer where I've made the changes I can share them here.
