### ISSUE TITLE
release on debian

### ISSUE THREAD

**Issue by monperrus** [jamiemcg/Remarkable#328]
Hi all,

thanks for the great tool.

any plan to push it as official Debian package on testing or sid? that would be super useful.

Thanks! --Martin

**Comment by phgachoud** [comment]
Personnaly still have a girl1.2 not instalable dependency issue

myHost$ apti /tmp/remarkable_1.87_all.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'remarkable' instead of '/tmp/remarkable_1.87_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 remarkable : Depends: gir1.2-webkit-3.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
myHost$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
`

**Comment by estiveljr** [comment]
I have the same issue on buster stable. I tried to install gir1.2-webkit-3.0 via apt but it keeps only the gir1.2-webkit-4.0,probably because it is the stable version.
I believe an update on dependencies could solve this.
If anyone knows a workaround please reply here.

**Comment by Jonny007-MKD** [comment]
+1
