### ISSUE TITLE
PDF export failed 

### ISSUE THREAD

**Issue by SAUCYSOUP76** [jamiemcg/Remarkable#338]
When attempting to export, i get the pop up; PDF export failed file export to PDF was unsuccessful

Also unable to close the file manager window when closing off the pop up message.

**Comment by Daniel-at-github** [comment]
Same here. My use case:

* Just installed `remarkable`
* Edited a file and saved it
* Tried to export to pdf and got an error window 
~~~
PDF Export Failed!!
File export to PDF was unsuccessful.
~~~
Console output
~~~
remarkable 2020-04-02.md 

Warning: Remarkable could not connect to the internet to check for updates

(process:13372): GLib-Net-WARNING **: 13:28:48.788: couldn't load TLS file database: Failed to open file ?/etc/ssl/certs/ca-certificates.crt?: Permission denied

(remarkable:13305): GLib-GIO-WARNING **: 13:30:20.626: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
Gtk-Message: 13:30:20.993: GtkDialog mapped without a transient parent. This is discouraged.

...

(remarkable:13305): dconf-WARNING **: 13:30:24.467: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.178" (uid=1000 pid=13305 comm="/snap/remarkable/5/usr/bin/python3 /snap/remarkabl") interface="ca.desrt.dconf.Writer" member="Change" error name="(unset)" requested_reply="0" destination="ca.desrt.dconf" (uid=1000 pid=2693 comm="/usr/lib/dconf/dconf-service ")
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.

Remarkable Error:	PDF Export Failed!!
~~~

Instalation process:
~~~ bash
sudo snap install remarkable
sudo snap list remarkable
~~~
~~~
Name        Version        Rev  Tracking       Publisher  Notes
remarkable  0+git.6f21d49  5    latest/stable  deadolus   -
~~~

Context:
~~~
inxi -S
System:    Host: aquilobuntu Kernel: 4.4.0-177-generic x86_64 (64 bit) Desktop: Unity 7.4.5
           Distro: Ubuntu 16.04 xenial
~~~

**Comment by Daniel-at-github** [comment]
Seen in https://askubuntu.com/questions/308128/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without

~~~ bash
export QT_DEBUG_PLUGINS=1
remarkable
~~~
Tried to export PDF Styled:
~~~
QFactoryLoader::QFactoryLoader() checking directory path "/snap/remarkable/5/usr/bin/platforms" ...
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.

Remarkable Error:	PDF Export Failed!!
~~~

Tried to fix it locally with no luck:
~~~
sudo ln -s /snap/remarkable/5/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms /snap/remarkable/5/usr/bin/platforms
ln: failed to create symbolic link '/snap/remarkable/5/usr/bin/platforms': Read-only file system
~~~

Maybe adding this simbolic link or creating file `qt.conf` following the instructions:
> Create file qt.conf in your project and add:
> ~~~
> [Paths]
> Plugins = /path/to/our/qt instalation/plugins
> ~~~
> https://doc.qt.io/qt-5/qt-conf.html

@jamiemcg, could you try this?

**Comment by pragomer** [comment]
Same issue here. On Ubuntu 20.04 (or Debian 10) remarkable is not useable at all, because deb installing fails because of dependencies; and snap package works, but PDF or HTML export does not work.

I got this same error message:

PDF Export Failed!!
File export to PDF was unsuccessful.

**Comment by pragomer** [comment]
The issue is because of Ubuntus Apparmor, I just found out:
`(remarkable:28834): dconf-WARNING **: 09:21:35.829: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.286" (uid=1000 pid=28834 comm="/snap/remarkable/5/usr/bin/python3 /snap/remarkabl" label="snap.remarkable.remarkable (enforce)") interface="ca.desrt.dconf.Writer" member="Change" error name="(unset)" requested_reply="0" destination="ca.desrt.dconf" (uid=1000 pid=1471 comm="/usr/libexec/dconf-service " label="unconfined")


`

**Comment by WalJT** [comment]
At first glance this seems to be related to how the snap is built. I noticed there's no  part [desktop helper](https://github.com/ubuntu/snapcraft-desktop-helpers) in the snapcraft.yaml. I ran into a similar issue when building the snap of [PyPLANE](https://github.com/m-squared96/PyPLANE). It turns out I needed the *desktop-qt5* part. This might be slightly trickier here, as Remarkable seems to use mostly GTK, but I'll build a snap locally and see if that fixes it.
