### ISSUE TITLE
How to install????

### ISSUE THREAD

**Issue by rogercreagh** [jamiemcg/Remarkable#353]
This looks like exactly what I need, but as a new-to-ubuntu/linux user I am lost by the complete lack of installation instructions.
On the website it says [quote] Easy installers are available for Debian, Ubuntu, Fedora[/quote] but there is no indication of how to install. 
Is there a repository command to use `apt-get instal...`? The download page offers .deb, .rpm and AUR downloads - presumably .deb is for Debian but which to use for Ubuntu and how to use it?
Even the Readme here on github is no more helpful.
Please provide a simple clue for a newbie - it'll only take a couple of words. Everything else I've installed tells me how to do it, why not this???

**Comment by joelnb** [comment]
The .deb is also for Ubuntu because Ubuntu is based on Debian. If you are on the latest Ubuntu release (20.04) you won't be able to install due to this issue https://github.com/jamiemcg/Remarkable/issues/351. If you are on an older Ubuntu you should be able to install by just downloading the .deb and double-clicking it - this will then prompt you whether you want to install it & ask for your password if you choose to do so.

If double-clicking doesn't work you could try this:

```
sudo dpkg -i remarkable_1.87_all.deb
sudo apt-get install -f
```

**Comment by rogercreagh** [comment]
Many thanks, just what I need. And thanks for including the commands as well as the double click.

We live and learn.

Roger

**Comment by appleyuchi** [comment]
https://blog.csdn.net/appleyuchi/article/details/107022438

here's the tutorial to install remarkable in ubuntu20.04
